name: Build Swift and Objective-C dylib

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
     - uses: actions/checkout@v4
     - run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
     - run: |
         swift package clean
         swift build -c release --product ui
         mkdir -p build
         cp .build/release/libui.dylib build/test.dylib

     - name: Upload dylib
       uses: actions/upload-artifact@v4
       with:
         name: test.dylib
         path: build/test.dylib
